---
  - hosts: loadbalancer
    become: true
    tasks: 
      - name: install nginx
        apt: name=nginx state=present update-cache=yes
    
      - name: ensure nginx started
        service: name=nginx state=started enabled=yes
