---
  - hosts: webserver
    become: true
    tasks: 
       - name: install web comps
         apt: name={{item}} state=present update-cache=yes
         with_items:
           - apache2
           - libapache2-mod-wsgi
           - python-pip
           - python-virtualenv

       - name: check apache2
         service: name=apache2 state=started enabled=yes

       - name: ensure mod_wsgi enabled
         apache2_module: state=present name=wsgi
         notify: restart apache2
       
       - name: copy demo app source
         copy: src=../demo/app/ dest=/var/www/demo mode=0755
         notify: restart apache2

       - name: copy apache virt config
         copy: src=../demo/demo.conf dest=/etc/apache2/sites-available/
         notify: restart apache2

    handlers:
      - name: restart apache2
        service: name=apache2 state=restarted
